# Generated by Django 3.0.5 on 2020-04-12 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_regi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codeinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('codename', models.CharField(max_length=200)),
                ('codedata', models.CharField(max_length=1000)),
            ],
        ),
    ]
