# Generated by Django 3.0.5 on 2020-04-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_codeinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeinfo',
            name='codedata',
            field=models.CharField(max_length=10000),
        ),
    ]
